### ISSUE TITLE
Now Could I use this package in production?

### ISSUE THREAD

**Issue by thearabbit** [mozfet/meteor-autoform-materialize#10]
I tried to `Meteor + React + Uniforms`, but it is difficult then `Meteor + Blaze + AutoForm`.
But i would like to use `Material`.
Now Could I use this package in production?

**Comment by mozfet** [comment]
Once you know AutoForm, using it is really easy. I mostly use it with SimpleSchema and Collections2, saving lots of time as opposed to hand rolled CRUD forms...

It works well enough for my needs, but I recommend checking out the playground to see what works and test what you need.

That being said, I have recently taken over this project and am preparing it for use in a large scale production myself, so will be working on stability and more features going forward. 

A lot is still missing before this is production ready in my opinion though, like unit tests, and I just did a large refactor to modernise the package - there may still be quite a few bugs. It should be nice a stable and relatively bug free in a few weeks, however a full test suite may take more time though.

Please help by reporting bugs or missing functionality and I will fix/add them as fast I can. Of course you are welcome to contribute to this project as well.

**Comment by thearabbit** [comment]
Thanks for your reply.
I will try soon.

**Comment by thearabbit** [comment]
Excuse me, could you share `Admin template of Materialize`?
before I use `AdminLte of Bootstrap`, but now I would to try `this`.

**Comment by mozfet** [comment]
I do not know what you mean, I have never worked with AdminLte before, I am not aware of an Admin template for Materialize… this is based on AutoForm…

Regards,
Wynand Vermeulen

**Comment by thearabbit** [comment]
I find the `Admin template of Materialize` for `Free`?
