### ISSUE TITLE
Problem with 'pickadateOptions: closeOnSelect, closeOnClear'

### ISSUE THREAD

**Issue by thearabbit** [mozfet/meteor-autoform-materialize#12]
Don't work
```js
dateFieldName: {
    type: Date
    autoform: {
      type:"pickadate"
      pickadateOptions:{
        closeOnSelect: true,
        closeOnClear: true
     }
    }
  }
```

**Comment by mozfet** [comment]
I will look at it today.

**Comment by mozfet** [comment]
I added this to the playground, and it seems to work fine... Can you elaborate on what is not working about it? 

```
dateWithOptions: {
    type: Date,
    label: 'Pick a date with options',
    autoform: {
      type: 'pickadate',
      pickadateOptions: {
        closeOnSelect: true,
        closeOnClear: true
     }
    }
  },
```

PS: I noticed your example looks similar to the pickadate example in the readme, and that some commas in that example and your example are missing... I already fixed the readme.

**Comment by mozfet** [comment]
I see you copied the text from the readme... I'll fix that...

**Comment by mozfet** [comment]
No feedback from therabbit, closing issue.
