### ISSUE TITLE
scss error

### ISSUE THREAD

**Issue by ghost** [mozfet/meteor-autoform-materialize#19]
/client/main.scss: Scss compiler error: File to import: ../node_modules/materialize-css/sass/components/_color.scss not found in file:

i got this error when trying to import css file from node module to main.scss

i think in the installation tutorial it should be meteor add fourseven:scss, not fourseven-scss

**Comment by mozfet** [comment]
Well spotted, I will fix it right now.

**Comment by mozfet** [comment]
Fixed the readme to add foursever:scss. Also republished to Atmosphere so that the instructions there is also updated.

**Comment by ghost** [comment]
What about my first question regarding error when trying to import the scss file?

**Comment by mozfet** [comment]
Aw, so sorry, I was lazy reading and thought the 1st was because of the second... Hmmm...

**Comment by mozfet** [comment]
Which version of MaterializeCSS are you using? The NPM package?

**Comment by ghost** [comment]
nope, meter add materialize:materialize, im using mateor package

**Comment by mozfet** [comment]
The Atmosphere Materialize package only contains compiled CSS, it does not include the SCSS. 

If you want to use SCSS, you need to use the NPM Package. You can still use Materialize Atmosphere if you are ok with it out of the box. This package no longer supports the Atmosphere package poetic:scss because that repo is no longer being maintained and is not necessary because we can use the NPM package directly from the source.

**Comment by ghost** [comment]
Following all the tutorial,  install from atmosphere,  install from npm,  but it stuck when creating main.scss and import from node modules...

**Comment by mozfet** [comment]
It works perfectly for my projects... have you tried looking at how its done in the playground?

**Comment by ghost** [comment]
i have it... following those playground, but still doesnt work, so now im using playground to start all my project, but i hope i can get explanation on that error. thanks

**Comment by mozfet** [comment]
Just checking, did you also install hammer using NPM? That had me stumped for a while. Do you have some logs or code you can share?

**Comment by mozfet** [comment]
I also assume you are using the latest versions of everything...

**Comment by ghost** [comment]
install all from the ground up, using all the latest version... its just stuck after create the main.scss file and import SASS in file /client/main.scss, i have deleted the project and start my project from your playground... but if you try to following the step in tutorial, it will reproduce the error. i will create the project again and send the log.

**Comment by ghost** [comment]
got the error..    While processing files with fourseven:scss (for target web.browser):
   /client/main.scss: Scss compiler error: File to import:
   ../node_modules/materialize-css/sass/components/_color.scss not found
   in file: C:/nodeprojects/myApp/{}/client/main.scss, but if i check in the node modules, those file are exist, i thought the problem with the path it has "{}" sign.. cmiww

**Comment by mozfet** [comment]
Hmmm... did you notice the scss-config.json file in the playground?

**Comment by mozfet** [comment]
I should probably add that part to the tutorial as well... it is part of the fourseven:scss configuration...

scss-config.json
```
{
  "includePaths": [
    "{}/node_modules/materialize-css/sass/"
  ]
}
```

**Comment by ghost** [comment]
it does not do the trick..... i have it in my projects as well

**Comment by mozfet** [comment]
Are you hot loading it? Try stopping meteor completely and start it up again. I found that config files are not always reliably reloaded when hot loading with Meteor.

**Comment by mozfet** [comment]
Also, clear your browser cache and try again.

**Comment by ghost** [comment]
yup, restart the server did it... thanks

**Comment by mozfet** [comment]
happy to be able to help
