### ISSUE TITLE
Issue with select-radio-inline (Cannot read property 'id' of undefined)

### ISSUE THREAD

**Issue by jfhenon** [mozfet/meteor-autoform-materialize#6]
First, thank you for taking over this project. I have an issue with the version 2.0.4 when I try to use the type "select-radio-inline".  It's easy to reproduce with your playground by changing the file
/meteor-autoform-materialize-playground/imports/api/schemas/example.js with 

select: {
    type: String,
    allowedValues: ['VALUE1', 'VALUE2'],
    autoform: {
      type: **'select-radio-inline'**
    }
  },

The console will then display the error message: Cannot read property 'id' of undefined ... 

Thanks

**Comment by mozfet** [comment]
Thx for opening the issue. Will look into it tomorrow.

**Comment by mozfet** [comment]
fixed in v2.0.8

**Comment by jfhenon** [comment]
Indeed. working now. Thank you.
